Laboratorio #1

Jhon Alex Salazar Rojas 

Zarina Ayelen Fuentes De Avila 

Laura Jimena Botero Sierra

Punto A:

En Python, las funciones se definen con la palabra clave def. Una función es un bloque de código que se ejecuta cuando se "llama", y sirve para reutilizar instrucciones sin tener que escribirlas varias veces. 

def nombre_funcion(parámetros):
    # Instrucciones
    return valor  # (opcional)


def → indica el inicio de la definición de la función.

nombre_funcion → nombre que identifica a la función.

parámetros → valores que recibe la función (pueden no existir).

return → devuelve un resultado (opcional).

In [19]:
#Ejemplo 

# 1. Función sin parámetros ni retorno
def saludar():
    print("Hola, bienvenido al programa de funciones en Python")

# 2. Función con parámetros
def saludar_persona(nombre):
    print(f"Hola {nombre}, ¡qué gusto verte!")

# 3. Función que devuelve un valor
def sumar(a, b):
    return a + b

# 4. Función con parámetro por defecto
def despedir(nombre="invitado"):
    print(f"Adiós, {nombre}. ¡Vuelve pronto!")

# 5. Función matemática (ejemplo de f(x) = x²)
def cuadrado(x):
    return x * x

# -----------------------------
# Llamando a todas las funciones
# -----------------------------

saludar()                               # sin parámetros
saludar_persona("Laura")                # con parámetro
print("La suma es:", sumar(5, 7))       # con retorno
despedir()                              # con parámetro por defecto
despedir("Juan")                        # sobreescribiendo valor por defecto
print("El cuadrado de 4 es:", cuadrado(4))  # función matemática

Hola, bienvenido al programa de funciones en Python
Hola Laura, ¡qué gusto verte!
La suma es: 12
Adiós, invitado. ¡Vuelve pronto!
Adiós, Juan. ¡Vuelve pronto!
El cuadrado de 4 es: 16


Punto B:

In [ ]:
def calculadora ():
    num1= int(input("Ingrese el primer numero: "))
    num2= int(input("Ingrese el segundo numero: "))
    opr= str(input ("Ingrese la operacion que desea realizar (+,-,*,/,%): "))
    if opr == "+":
        rslt= num1 + num2
    elif opr=="-":
        rslt= num1 - num2
    elif opr=="*":
        rslt= num1 * num2
    elif opr=="/":
        if num2== 0:
            rslt= ("No se puede dividir entre 0.")
        else:
            rslt= num1/num2
    elif opr =="%":
        rslt= num1 % num2
    print("El resultado es: ", rslt)

calculadora()

El resultado es:  5.0


Punto C:

In [ ]:
import numpy as np
n=int(input("Ingrese el parametro del tamaño de la matriz cuadrada: "))
matriz=np.zeros((n, n), dtype=float)  
for i in range(n):
    for j in range(n):
        valor=float(input(f"Ingrese el dato para la Fila ({i+1}), Columna ({j+1}): "))
        matriz[i,j]=valor
print("La matriz ingresada es: \n",  matriz)
transpuesta=matriz.T
print("La transpuesta de la matriz es: \n", transpuesta )



La matriz ingresada es: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
La transpuesta de la matriz es: 
 [[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


Punto D:

In [18]:
dia=int(input("ingrese un dia: "))
mes=str(input("Ingrese un mes: ").lower())

if mes=="marzo" and dia>=21 and dia<=31:
  print ("En este dia de ", mes,"estariamos en primavera")
elif mes=="abril" and dia>=1 and dia<=30:
  print ("En este dia de ", mes,"estariamos en primavera")
elif mes=="mayo" and dia>=1 and dia<=31:
  print ("En este dia de ", mes,"estariamos en primavera")
elif mes=="junio" and dia>=1 and dia<=21:
  print ("En este dia de ", mes,"estariamos en primavera")
elif mes=="junio" and dia>=22 and dia<=30:
  print ("En este dia de ", mes,"estariamos en verano")
elif mes=="julio" and dia>=1 and dia<=31:
  print ("En este dia de ", mes,"estariamos en verano")
elif mes=="agosto" and dia>=1 and dia<=30:
  print ("En este dia de ", mes,"estariamos en verano")
elif mes=="septiempre" and dia>=1 and dia<=23:
  print ("En este dia de ", mes,"estariamos en verano")
elif mes=="septiempre" and dia>=24 and dia<=30:
  print ("En este dia de ", mes,"estariamos en otoño")
elif mes=="octubre" and dia>=1 and dia<=31:
  print ("En este dia de ", mes,"estariamos en otoño")
elif mes=="noviembre" and dia>=1 and dia<=30:
  print ("En este dia de ", mes,"estariamos en otoño")
elif mes=="diciembre" and dia>=1 and dia<=22:
  print ("En este dia de ", mes,"estariamos en otoño")
elif mes=="diciembre" and dia>=22 and dia<=31:
  print ("En este dia de ", mes,"estariamos en invierno")
elif mes=="enero" and dia>=1 and dia<=31:
  print ("En este dia de ", mes,"estariamos en invierno")
elif mes=="febrero" and dia>=1 and dia<=28:
  print ("En este dia de ", mes,"estariamos en invierno")
elif mes=="marzo" and dia>=21 and dia<=31:
  print ("En este dia de ", mes,"estariamos en invierno")
else:
    print("Ingrese un mes o dia valido")

En este dia de  febrero estariamos en invierno


Punto E:

In [20]:
import numpy as np

filas=int(input("Ingrese el numero de filas: "))
columnas=int(input("Ingrese el numero de columnas: "))
print("\n Ingrese los elementos de la matriz: ")



matriz_usuario=[]
for i in range(filas):
    fila=[]
    for j in range(columnas):
        valor=int(input(f"Elemento [{i+1},{i+j}]: "))
        fila.append(valor)
    matriz_usuario.append(fila)

matriz_usuario=np.array(matriz_usuario)

matriz_aleatoria=np.random.randint(0,10, (filas, columnas))
resultado=matriz_aleatoria + matriz_usuario

print("\n Matriz Ingresada: \n", matriz_usuario)
print("\n Matriz Aleatoria: \n", matriz_aleatoria)
print("\n Suma de ambas: \n", resultado)


 Ingrese los elementos de la matriz: 

 Matriz Ingresada: 
 [[1 2 3]
 [4 5 6]]

 Matriz Aleatoria: 
 [[9 8 9]
 [6 3 2]]

 Suma de ambas: 
 [[10 10 12]
 [10  8  8]]


Punto F:

In [1]:
reseñas=[]


while True:
    reseña=input("Escribe una reseña: ")

    if reseña.lower() == "fin": 
        if len(reseñas) >= 3: 
            break
        else: 
            print("Debe ingresar minimo 3 reseñas para terminar.")
    else:
        reseñas.append(reseña)


import string 

palabras=[]

for reseña in reseñas:
    reseña=reseña.lower()
    for signo in ".!,?":
        reseña=reseña.replace(signo,"")
    palabras.extend(reseña.split())

frecuencias={}
for palabra in palabras:
    if palabra in frecuencias:
        frecuencias[palabra] += 1
    else:
        frecuencias[palabra] = 1


print("\nDiccionario de Frecuencias: ")
print(frecuencias)

mas_frecuentes = sorted(frecuencias.items(), key=lambda x: x[1], reverse=True)[:3]
print("\n Las 3 palabras más frecuentes en las reseñas son:")
for palabra, freq in mas_frecuentes:
    print(f"{palabra} aparece {freq} veces")


Diccionario de Frecuencias: 
{'comida': 4, 'maluca': 2, 'y': 3, 'meseras': 3, 'lindas': 1, 'linda': 1, 'mas': 2, 'desagradable': 1, 'buenisima': 1, 'aun': 1, 'mejor': 1}

 Las 3 palabras más frecuentes en las reseñas son:
comida aparece 4 veces
y aparece 3 veces
meseras aparece 3 veces
